export const ROLES = {
    USER: "user",
    ADMIN: "admin"
};

export const ACCOUNT_STATUS = {
    PENDING: "PENDING",
    ACTIVE: "ACTIVE",
    SUSPENDED: "SUSPENDED",
    BLOCKED: "BLOCKED"
};

export const LISTING_STATUS = {
    PENDING: "PENDING",
    ACTIVE: "ACTIVE",
    SOLD: "SOLD",
    REMOVED: "REMOVED",
    REJECTED: "REJECTED",
    PENDING_COMMISSION: "PENDING_COMMISSION"
};

export const INSPECTION_STATUS = {
    PENDING: "PENDING",
    PENDING_COORDINATION: "PENDING_COORDINATION",
    SCHEDULED: "SCHEDULED",
    COMPLETED: "COMPLETED",
    CANCELLED: "CANCELLED"
};